### ISSUE TITLE
Forward to custom smtp port

### ISSUE THREAD

**Issue by LecrisUT** [mailway-app/mailout#2]
I have just found out about this project from reddit, and would like to know if this project will support this feature either free or paid. For context I am currently using [mxguarddog](https://mxguarddog.com/) to forward my emails to my local mail-server on a different SMTP port due to isp block. Problem there is that it has an aggressive spam filter which I actually do not wish for and it is not open-source. Could this project accommodate these needs?

At the minimum it should be able to redirect incoming emails to the provided port(s) in at least three configurations:
  -  Transparent: emails are simply forwarded without mailway reading  any metadata except the destination domain name.
  - Holding: emails are temporarily received on the mailway server, then redirected to the first destination port which accepts it. It should retry for at least 24h and inform the domain owner if there are issues.
  - Managed: similar to the current method but with ability to redirect to smtp port as well.

**Comment by xtuc** [comment]
@LecrisUT I implemented a way for the email to be forwarded to a custom smtp port and it works on the public service. Would you want to beta that the feature? Since I'm still working on its documentation, I can invite you to a Slack to help you set it up.

Please send me a email on the address on my profile, I'll invite you.

**Comment by LecrisUT** [comment]
Yes I'm willing to beta test. I've sent an email from the address linked to my profile. It passes all of the checks on mail-tester.com, but if it doesn't arrive or is flagged as spam, let me know. The return mail on the other hand will certainly be flagged by mxguarddog as I previously complained about, but I'll keep an eye out for it.

**Comment by LecrisUT** [comment]
Basic functionality works so far. I will create separate issues to track the detailed configuration issues
